domain: katrin-yoga-classes.github.io
url: https://katrin-yoga-classes.github.io
baseurl: "/wind"

title: Katrin Yoga Classes
email: katrin.yoga.classes@gmail.com
author: Katrin 

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "katrin.yoga.classes@gmail.com"
